# Generated by Django 4.2 on 2023-08-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('G', 'Grocery'), ('B', 'Beauty product'), ('E', 'Electronics'), ('H', 'Home_decorate'), ('D', 'Offer'), ('F', 'Furniture'), ('A', 'Applinces')], max_length=2),
        ),
    ]
